### ISSUE TITLE
User Pref: Invisibles (spaces, line endings) are overridden and disappear.

### ISSUE THREAD

**Issue by johnathankent** [mariozaizar/language-eml#11]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked that your issue isn't already filed: https://github.com/mariozaizar/language-eml/issues

### Description

Whitespace chars (spaces, line endings) disappear when on and this package is enabled.

gif of the bug: http://recordit.co/DpW4atxszp

### Steps to Reproduce

1. Enable whitespace chars in editor settings
2. Disabled all community (non-core) packages
3. Enabled Package

**Expected behavior:**

1. Whitespace pref should not override user pref or theme.
2. Whitespace chars should be visible when enabled in editor settings and this package is enabled. 

**Actual behavior:**

Whitespace chars (spaces, line endings) disappear when on and this package is enabled.

**Reproduces how often:**

100%

### Versions
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

macOS 10.12.4 (Sierra)

**Comment by mariozaizar** [comment]
Thanks for this awesome issue report @johnathankent.

I removed the global modifiers from the settings. 
My apologies that it took so long.
