### ISSUE TITLE
Enabling package makes all editors ignore line wrapping settings

### ISSUE THREAD

**Issue by abelhegedus** [mariozaizar/language-eml#12]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked that your issue isn't already filed: https://github.com/mariozaizar/language-eml/issues

### Description

When language-eml package is enabled, all editors have soft wrapping at 80 characters regardless of global settings or package level settings.

### Steps to Reproduce

1. Enable language-eml package
1. Check that global preferred line length is set to a value other than 80
1. Open any file (e.g. MyClass.java), content type is _not_ Email
1. Lines are wrapped at 80 character
1. Disable language-eml package
1. Lines are wrapped at proper settings

**Expected behavior:** [What you expect to happen]

Language-eml package should respect global and package level wrapping settings and only affect an editor when the content type is Email.

**Actual behavior:** [What actually happens]

Lines are wrapped at 80 character, no matter what the user puts in settings.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

OS: Microsoft Windows [Version 10.0.15063]

$ atom --version
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ apm --version
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 3.6.1
git 2.13.0.windows.1
visual studio

**Comment by mariozaizar** [comment]
Thanks for the report!  This should be fixed with [v0.7.1](https://github.com/mariozaizar/language-eml/blob/master/CHANGELOG.md#v071-2017-08-17).
