### ISSUE TITLE
IPv6 matching incomplete

### ISSUE THREAD

**Issue by wesinator** [mariozaizar/language-eml#21]
### Description of the bug
IPv6 highlighting is not complete, does not highlight the last 'octet'

### Steps to reproduce

```eml
Received: from prod.exchangelabs.com (2a01:111:e400:7a4d::52) by
```
![image](https://user-images.githubusercontent.com/5124946/50493372-20934e00-09eb-11e9-96cd-255829f85ae0.png)

### Expected behavior

IPv6 addresses either highlighted fully or not highlighted.

* Atom version: 1.33.1
* APM version: 2.1.2

**Comment by mariozaizar** [comment]
Thanks for the report, sorry for the late response!
I'm happy to be back after paternity leave 🍼 😅

**Comment by wesinator** [comment]
> Thanks for the report, sorry for the late response!
> I'm happy to be back after paternity leave

@mariozaizar Congratulations !
